
from django.db import models
from django.conf import settings

class Project(models.Model):
    """
    Represents a single mobile app project created by a user.
    """
    class AppType(models.TextChoices):
        ANDROID = 'ANDROID', 'Android'
        IOS = 'IOS', 'iOS'
        BOTH = 'BOTH', 'Both'

    class ProjectStatus(models.TextChoices):
        ANALYSIS_PENDING = 'ANALYSIS_PENDING', 'Analysis Pending'
        ANALYSIS_COMPLETE = 'ANALYSIS_COMPLETE', 'Analysis Complete'
        DESIGN_PENDING = 'DESIGN_PENDING', 'Design Pending'
        DESIGN_COMPLETE = 'DESIGN_COMPLETE', 'Design Complete'
        CODE_GENERATION = 'CODE_GENERATION', 'Code Generation'
        COMPLETED = 'COMPLETED', 'Completed'
        FAILED = 'FAILED', 'Failed'

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='projects')
    name = models.CharField(max_length=255)
    source_url = models.URLField(max_length=500)
    analytics_data_url = models.URLField(max_length=500, blank=True, null=True)
    app_type = models.CharField(max_length=10, choices=AppType.choices)
    status = models.CharField(max_length=20, choices=ProjectStatus.choices, default=ProjectStatus.ANALYSIS_PENDING)
    status_message = models.CharField(max_length=255, blank=True, null=True, help_text="A user-facing message about the current status.")
    
    # AI-Generated Fields
    user_persona_document = models.TextField(blank=True, null=True, help_text="Generated by the Market Analyst Agent.")
    brand_palette = models.JSONField(blank=True, null=True, help_text="Generated by the Design Agent.")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} by {self.owner.username}"
